kind: Pod
apiVersion: v1 
metadata:
  name: pod-env
spec: 
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course 
          value: kubernetes 
        - name: duration 
          value: 25Hrs 
        - name: trainer 
          value: kedar 
        - name: envin_containers 
          value: hello wellcome to the key value pairs 
          